backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "NewPage", name: "newPage", widget: "hidden", default: "true"}
      - {label: "Überschrift", name: "title", widget: "string"}
      - {label: "Unterüberschrift", name: "subheadline", widget: "text"}
      - {label: "Verröffentlichumsdatum", name: "date", widget: "datetime"}
      - {label: "Vorschaubild auf Übersichtsseite", name: "previewImage", widget: "image"}
      - {label: "Bild über dem Blogartikel", name: "blogImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/indexpage/index.md"
        label: "Startseite"
        name: "home"
        fields:
           - {label: Bühne, name: stage, widget: object, fields: [{label: Bild, name: image, widget: image}, {label: Überschrift, name: headline, widget: string}, {label: Unterüberschrift, name: subHeadline, widget: string}, {label: Linkziel, name: buttonTarget, widget: string}, {label: Linktext, name: buttonText, widget: string}]}
           - {label: Bildteaser, name: featuredProducts, widget: list, fields: [{label: Bild, name: image, widget: image}, {label: Überschrift, name: headline, widget: string}, {label: Linkziel, name: linkTarget, widget: string}, {label: Neuen Tab öffnen, name: blank, widget: select, options: [{label: Ja, value: true}, {label: Nein, value: false}]}]}
           - {label: Vorstellung, name: wideTeaser, widget: object, fields: [{label: Überschrift, name: headline, widget: string}, {label: Beschreibung, name: description, widget: text}]}
      - file: "src/pages/about/index.md"
        label: "Über uns"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Bühne, name: stage, widget: object, fields: [{label: Bild, name: image, widget: image}, {label: Überschrift, name: headline, widget: string}, {label: Unterüberschrift, name: subheadline, widget: string}, {label: Linkziel, name: buttonTarget, widget: string}, {label: Linktext, name: buttonText, widget: string}]}
          - {label: Über uns Beschreibung, name: description, widget: text}